export const listOfGoofers = [
    {
      id: "233aash01",
      name: "saheed bello",
      profession: "Driver",
      experience: "Mid-level",
      category: "Transport",
      avrRank: 3.5,
      salaryExp: 200000,
      age: 24,
    },
    {
      id: "233aash02",
      name: "Johnson Tade",
      profession: "Driver",
      experience: "Expert",
      category: "Transport",
      avrRank: 4.5,
      salaryExp: 400000,
      age: 31,
    },
    {
      id: "233aash03",
      name: "Akinyele Adeyemi",
      profession: "FrontEnd Engineer",
      experience: "Mid-level",
      category: "Developer",
      avrRank: 4.5,
      salaryExp: 600000,
      age: 30,
    },
    {
      id: "233aash04",
      name: "Adekorede Adeyemi",
      profession: "Backend",
      experience: "Mid-level",
      category: "Developer",
      avrRank: 4.5,
      salaryExp: 500000,
      age: 33,
    },
    {
      id: "233aash05",
      name: "Emmanuel Uchewa",
      profession: "Backend",
      experience: "Mid-level",
      category: "Developer",
      avrRank: 4.5,
      salaryExp: 500000,
      age: 33,
    },
    {
      id: "233aash06",
      name: "Olaiya Zechariah",
      profession: "Backend",
      experience: "Mid-level",
      category: "Developer",
      avrRank: 4.5,
      salaryExp: 500000,
      age: 33,
    },
    {
      id: "233aash07",
      name: "Angela Yu",
      profession: "Doctor",
      experience: "Mid-level",
      category: "Healthcare",
      avrRank: 4.5,
      salaryExp: 200000,
      age: 35,
    },
    {
        id: "233aash08",
        name: "Mercy Johnson",
        profession: "Electrician",
        experience: "Mid-level",
        category: "Engineering",
        avrRank: 3.5,
        salaryExp: 200000,
        age: 24,
      },
      {
        id: "233aash09",
        name: "Johnson John",
        profession: "Carpenter",
        experience: "Mid-level",
        category: "Carpentry",
        avrRank: 4.5,
        salaryExp: 400000,
        age: 31,
      },
      {
        id: "233aash10",
        name: "Ololere Ayomide",
        profession: "Carpenter",
        experience: "Mid-level",
        category: "Carpentry",
        avrRank: 4.5,
        salaryExp: 60000,
        age: 30,
      },
      {
        id: "233aash11",
        name: "Fadushi Ridwan",
        profession: "Carpenter",
        experience: "Mid-level",
        category: "Carpentry",
        avrRank: 4.5,
        salaryExp: 60000,
        age: 30,
      },
      {
        id: "233aash12",
        name: "Dauda Tommy",
        profession: "Carpenter",
        experience: "Mid-level",
        category: "Carpentry",
        avrRank: 4.5,
        salaryExp: 60000,
        age: 30,
      },
      {
        id: "233aash04",
        name: "Adekorede Adeyemi",
        profession: "Backend",
        experience: "Mid-level",
        category: "Developer",
        avrRank: 4.5,
        salaryExp: 500000,
        age: 33,
      },
      {
        id: "233aash05",
        name: "Emmanuel Uchewa",
        profession: "Backend",
        experience: "Mid-level",
        category: "Developer",
        avrRank: 4.5,
        salaryExp: 500000,
        age: 33,
      },
      {
        id: "233aash06",
        name: "Olaiya Zechariah",
        profession: "Backend",
        experience: "Mid-level",
        category: "Developer",
        avrRank: 4.5,
        salaryExp: 500000,
        age: 33,
      },
      {
        id: "233aash07",
        name: "Angela Yu",
        profession: "Doctor",
        experience: "Mid-level",
        category: "Healthcare",
        avrRank: 4.5,
        salaryExp: 200000,
        age: 35,
      },
  ];